name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t chaitalimane/shopping-cart
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    - run: docker push chaitalimane/shopping-cart
